const boyNames = [
  "Pete Blackbeard",
  "Bill Bones",
  "Peteplank",
  "Black Bill The Feared",
  "Wainwright ‘Bird Eye’ Shelley",
  "John Blackeye",
  "Poopdeck Pete",
  "Big Jones",
  "Maximus Dark-Skull",
  "Toothless Pete",
  "Crimson Seadog",
  "Musclemouth Mike",
  "Winter Greybeard",
  "Chipper Goldheart",
  "Thunder Dave",
  "Stinkin’ Pete",
  "Davey Dark-Skull",
  "Old-Tide Sammy",
  "Pistol-Grin Gary",
  "Old Chipper",
  "One-Tooth John",
  "Hunter Brendan",
  "Speechless Mike",
  "Mad Michael",
  "Handsome Jimmy",
  "Rascal Jimmy",
  "Cannonball Conner",
  "Jason Sea Legs",
  "Barnacle Bill",
  "Silver-Tooth Samuel",
  "Pete Peg-Leg",
  "Lazy-Eye Louie",
  "Paddy Sparrow",
  "Vince Puffypants",
  "Jack Red-Locks",
  "Gordon Rough",
  "Oscar Foul",
  "Wyatt Gold",
  "Edwin ‘No Money’ Mables",
  "Theo Stinkalot",
  "George Balding",
  "Hansel The Handsome",
  "Jonas Rattler",
  "Jacob Cutter",
  "Wade Wilds",
  "Randell Rummy",
  "Garrick Roach",
  "Malvo Razor-Face",
  "Roger Starky",
  "Finn O’Fish",
  "Dirty Danny",
  "Churchhill Evans ",
  "Peg Leg Pete",
  "Hook Hand Hank",
  //girl names underneath here
  "Celia ‘Butcher’ Tyde",
  "Elnora ‘Evil Grin’ Neale",
  "Shiverin’ Shelley",
  "Mighty Mary",
  "Kellie Strong-Heart",
  "Misty Winters",
  "Voodoo Wendy",
  "Salty Sarah",
  "Shark-Fin Suzie",
  "Penelope Precious",
  "Sugar-Tongue Shelly",
  "Silvera Snake-Eyes",
  "Boney Brenda",
  "One-Leg Nellie",
  "One-Eye Wendy",
  "Lady Tide",
  "Cut-Throat Connie",
  "Nancy Tall-Tide",
  "Moonie Two-Toe",
  "Esme Dark-Waters",
  "Jilly Buckets",
  "Mary Gun-Powder",
  "Liza Mcgee",
  "Sadie Waters",
  "Joy McStubby",
  "Betty Tuna-Breath",
  "Opal Sea-Wolf",
  "Nancy Lobster-Legs",
  "Bella O’Greed",
  "Ella Treasures",
  "Ruth O’Patches",
  "Miranda Gold-Tooth",
  "Vera Sparrow",
  "Carrie Atlantis",
  "Mazie Deep-Waters",
  "Peggy One-Leg",
  "Evie Shark-Bait",
  "Lou-Lou Stubbs",
  "Polly d’Plank",
  "Pearl Bailey",
  "Glory Jones",
  "Clara Shadows",
  "Sally Black",
  "Daisy O’Jelly",
  "Suzie McGraw",
  "Janie Big-Lips",
  "Vicky FishMonger",
  "Mabel Hook-Hand",
  "Mae Whiskey-Woo",
  "Martha One-Eyed",
  "Crazy Kellie",
  "Lady Cassandra",
  "Lady Marilyn Man-Eater",
  "Mary Jane Death-Bringer",
];

export const randomCrewMateName = () => {
  return boyNames[Math.floor(Math.random() * boyNames.length)];
};

const icons = [
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/004-pirate-3.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/005-pirate-hat.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/006-pirate-4.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/007-pirate-5.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/008-pirate-6.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/009-pirate-7.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/010-pirate-8.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/011-pirate-9.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/012-pirate-10.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/013-pirate-11.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/014-pirate-12.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/015-pirate-13.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/016-pirate-14.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/017-pirate-15.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/018-pirate-16.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/019-pirate-17.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/020-pirate-18.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/021-pirate-19.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/022-pirate-20.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/023-pirate-21.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/024-pirate-22.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/025-pirate-23.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/026-pirate-24.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/027-pirate-25.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/028-pirate-26.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/029-pirate-27.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/030-pirate-28.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/031-pirate-29.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/032-pirate-30.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/1-pirate.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/2-pirate.png",
  "https://nicolas-bucket-recipe-app-images.s3.us-east-2.amazonaws.com/Pirate-looter-icons/Pirate-Icons/3-pirate.png",
];

export const randomCrewAttributes = () => {
  return [];
};

export const randomCrewIcon = () => {
  return icons[Math.floor(Math.random() * icons.length)];
};
