const eventCards = [
  {
    name: "cardName",
    description: "",
    leftChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    rightChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "Whirlpools",
    description:
      "One of your crew mates notices a small spiral forming in the water. 'WHIRLPOOOOLS!!!' he shouts. ",
    leftChoice: {
      text: "Dogde, Duck, Dip, Dive and Dodge the whirlpools.",
      gold: 0,
      moral: 10,
      health: -20,
      energy: -30,
    },
    rightChoice: {
      text: "Go the long way around. Like a wise Captain should.",
      gold: 0,
      moral: -10,
      health: 0,
      energy: -30,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "Kraken Encounter",
    description:
      "The sea splits open and your boat trembles as you see giant tentacles grasp your ship. In the Krakens eyes, you seem to see it seeks something.",
    leftChoice: {
      text: "Give up some gold.",
      gold: -20,
      moral: 20,
      health: -10,
      energy: 0,
    },
    rightChoice: {
      text: "Give up a crew mate.",
      gold: 20,
      moral: -20,
      health: -30,
      energy: 0,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "Storm",
    description:
      "What started as a few drops has now evolved into a whirlwind of rain and ocean.Your crew is soaking wet but listening for your orders.",
    leftChoice: {
      text: "Go wait below deck. It's quiet crowded here.",
      gold: 0,
      moral: -10,
      health: 0,
      energy: 10,
    },
    rightChoice: {
      text: "Power through like the mighty Pirates you are!",
      gold: 0,
      moral: 10,
      health: 0,
      energy: -20,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "Floating Object",
    description:
      " While removing one of the barnacles from the ship. A crew mate notices a floating object. ",
    leftChoice: {
      text: "Reel it in.",
      gold: 0,
      moral: 0,
      health: 0,
      energy: -10,
      useSecondAction: true,
    },
    rightChoice: {
      text: "Keep sailing",
      gold: 0,
      moral: -10,
      health: 0,
      energy: 0,
    },
    secondAction: {
      items: [
        {
          name: "Keg of Rhum",
          text: "As you pull the object over. Your crew grins from ear to ear! It is a great day to be a pirate!",
          gold: 0,
          moral: 30,
          health: 10,
          energy: 0,
        },
        {
          name: "Box of Oranges",
          text: "Vitamin C is nothing to scoff at. Everyone eats a few and feels much better. ",
          gold: 0,
          moral: 0,
          health: 30,
          energy: 20,
        },
        {
          name: "Poutch of Gold",
          text: "Faint clinging of the coins as you reel it in. This trip is already a success!",
          gold: 20,
          moral: 0,
          health: 0,
          energy: 0,
        },
        {
          name: "Letters",
          text: "While opening the barrel, lost letters start pouring out. Too wet to read.",
          gold: 0,
          moral: 0,
          health: 0,
          energy: 0,
        },
        {
          name: "Clothes",
          text: "A tightly closed box is pried open,showing leather clothes. The crew will sleep in the warmth tonight!",
          gold: 0,
          moral: 0,
          health: 0,
          energy: 30,
        },
        {
          name: "Cursed Skull",
          text: "As you pry open the box a cold wind goes down your spine, your crew loose determination to carry on...",
          gold: 0,
          moral: -30,
          health: 0,
          energy: 0,
        },
        {
          name: "Music Box",
          text: "Dripping with water but still managing to work, one crew mate spins it up and everyone has a little dance.",
          gold: 0,
          moral: 30,
          health: 0,
          energy: 0,
        },
        {
          name: "Spoil Food",
          text: "One of the crew fancy's himself a cook and convices everyone to eat the spoiled... what ever it was.",
          gold: 0,
          moral: -10,
          health: -20,
          energy: 0,
        },
        {
          name: "Sea Monkey",
          text: "Once the box dropped on deck it breaks and spills with water, a Sea Monkey jumps at your gold poutch and leaps into the sea with it.",
          gold: -20,
          moral: 0,
          health: 0,
          energy: 0,
        },
        {
          name: "Fresh Wood",
          text: "This must not of been floating for long! Let's use it to repair the ship!",
          gold: 0,
          moral: 0,
          health: 10,
          energy: 0,
        },
      ],
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "Peaceful voyage",
    description:
      "The sea is calm and so are the skies. Sails in the wind, everything is going well. A sailors life for us!",
    leftChoice: {
      text: "Excellent!",
      gold: 0,
      moral: 10,
      health: 0,
      energy: 0,
    },
    rightChoice: {
      text: "Excellent",
      gold: 0,
      moral: 10,
      health: 0,
      energy: 0,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "Boat Leak",
    description:
      "The ship suddenly gets a loud thud on the bottom of it. Then faint running water. A small leak has sprung!",
    leftChoice: {
      text: "Repair it at once!",
      gold: 0,
      moral: 0,
      health: -10,
      energy: -20,
    },
    rightChoice: {
      text: "A small leak never bothered anyone.",
      gold: 0,
      moral: -20,
      health: -20,
      energy: 0,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "Pirates",
    description:
      "A boat is a approaching and you can see by the flag! They are Pirates and they are looking for trouble!",
    leftChoice: {
      text: "Give them gold and keep going. ",
      gold: -30,
      moral: -20,
      health: 0,
      energy: 0,
    },
    rightChoice: {
      text: "Refuse to pay and fight!",
      gold: 0,
      moral: +10,
      health: -20,
      energy: -20,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "Privateers",
    description:
      "A boat approaches with a privateers flag. They have a big crew and a bigger Cannon.",
    leftChoice: {
      text: "Deploy the sails and go as fast as you can!!",
      gold: 0,
      moral: +10,
      health: -30,
      energy: -30,
    },
    rightChoice: {
      text: "Try to sweet talk your way out of this.",
      gold: 0,
      moral: 0,
      health: 0,
      energy: -10,
      useSecondAction: true,
    },
    secondAction: {
      secondChoices: {
        description:
          "The privateers listened for a few sentences and decided payement was still due.",
        leftChoice: {
          text: "Accept and pay the toll.",
          gold: -40,
          moral: -20,
          health: 0,
          energy: 0,
        },
        rightChoice: {
          text: "Dance around to pay less taxes.",
          gold: -10,
          moral: -10,
          health: 0,
          energy: -20,
        },
      },
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "cardName",
    description: "",
    leftChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    rightChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "cardName",
    description: "",
    leftChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    rightChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "cardName",
    description: "",
    leftChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    rightChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "cardName",
    description: "",
    leftChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    rightChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "cardName",
    description: "",
    leftChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    rightChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "cardName",
    description: "",
    leftChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    rightChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "cardName",
    description: "",
    leftChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    rightChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "cardName",
    description: "",
    leftChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    rightChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "cardName",
    description: "",
    leftChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    rightChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "cardName",
    description: "",
    leftChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    rightChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "cardName",
    description: "",
    leftChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    rightChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "cardName",
    description: "",
    leftChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    rightChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "cardName",
    description: "",
    leftChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    rightChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "cardName",
    description: "",
    leftChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    rightChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "cardName",
    description: "",
    leftChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    rightChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "cardName",
    description: "",
    leftChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    rightChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "cardName",
    description: "",
    leftChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    rightChoice: {
      text: "",
      gold: 0,
      moral: 0,
      health: 0,
      energy: 0,
    },
    image: "this will be where we put the image sprite for the card",
  },
];

const endCards = [
  {
    name: "Empty Moral",
    description:
      "With your crews moral at the complete floor, no one wants to paddle. No one wants to move.This is the end.",
    leftChoice: {
      text: "Ok",
    },
    rightChoice: {
      text: "Ok",
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "Full Moral",
    description:
      "Your crew is happy. Too happy... They think you have gone soft and are not fit to be their Pirate Captain. They staged a mutiny and threw you off the ship.",
    leftChoice: {
      text: "how dare they.",
    },
    rightChoice: {
      text: "how dare they.",
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "Empty Ship Health",
    description:
      "Your ship has just took it's last hit. As a good Captain. You are sinking with your beloved.",
    leftChoice: {
      text: "A true pirate's end.",
    },
    rightChoice: {
      text: "A true pirate's end.",
    },
    image: "this will be where we put the image sprite for the card",
  },
  {
    name: "Empty Energy",
    description:
      "As you try to shout at your crew orders. Your throat runs dry and your vision blurs. A loud 'thud' is heard, and you, the captain, never said an other word.",
    leftChoice: {
      text: "walk towards the light",
    },
    rightChoice: {
      text: "walk towards the light",
    },
    image: "this will be where we put the image sprite for the card",
  },
];
