const boatNames = [
  `Abandoned Barnacle`,
  `Angel of Doom`,
  `Barbaric Serpent`,
  `Black Pearl`,
  `Blood Lightening`,
  `Blood-Thirsty Rover`,
  `Bloody Hangman`,
  `Bone Heart`,
  `Bone Rattler`,
  `Broken Slave`,
  `Broken Soul`,
  `Burning Rose`,
  `Cannon Blocker`,
  `Corrupted Skull`,
  `Crooked Star`,
  `Cursed Hangman`,
  `Cursed Raider`,
  `Cursed Slave`,
  `Dark Howler`,
  `Dark Soul`,
  `Dazzling Pearl`,
  `Dead Bones`,
  `Dead-Man’s Raft`,
  `Death Fire`,
  `Demon Sea-Dog`,
  `Disgraced Anchor`,
  `Dream Chaser`,
  `Drunken James`,
  `Drunken Sailor`,
  `Fearful Diamond`,
  `Fearful Slave`,
  `Ginger Snap`,
  `Golden Cairn`,
  `Golden Eel`,
  `Golden Jewel`,
  `Golden Mermaid`,
  `Golden Rose`,
  `Golden Squid`,
  `Grand Serpent`,
  `Hangman’s Hollow`,
  `Happy Sailor`,
  `Hellish Captain`,
  `Hungry Hangman`,
  `Jolly Skull`,
  `Jolly Storm`,
  `Lone Star`,
  `Lost Dreams`,
  `Lost King`,
  `Lost Lagoon`,
  `Lost Soul`,
  `Lost Treasure`,
  `Moon Raider`,
  `Moon Whisperer`,
  `Night Blood`,
  `Night Fighter`,
  `Night of Doom`,
  `Night Soul`,
  `Night Wind`,
  `Ocean Curse`,
  `Old Barnacle`,
  `Old James`,
  `Old Scallywag`,
  `Old Sea Dog`,
  `Old Tide`,
  `Plague Lagoon`,
  `Plague Storm`,
  `Poisoned Arrow`,
  `Poisonous Maid`,
  `Red Hurricane`,
  `Red Pirate`,
  `Red Wave`,
  `Revenge Queen`,
  `Revenge Tide`,
  `Rising Ghost`,
  `Ruthless Raider`,
  `Scream Fire`,
  `Sea Ghost`,
  `Sea of Terror`,
  `Secret Dagger`,
  `Serpent’s Cry`,
  `Seven Seas of WIlliams`,
  `Shadow Storm`,
  `Shark Rider`,
  `Sick Walrus`,
  `Silent Raider`,
  `Soggy Seaweed`,
  `Soul Cairn`,
  `Speedy Sun`,
  `Stinkin Plank`,
  `Stinkin Skull`,
  `Sun Howler`,
  `Tainted Heart`,
  `Tainted Rose`,
  `Thunder Tide`,
  `Thunder Waves`,
  `Vanilla Skyline`,
  `White Night`,
  `White Wave`,
  `Wild Storm`,
  `Wind Raider`,
  `Drunken Squid`,
  `Shallow Mermaid`,
  `Mystic Sea`,
  `Pirate’s Secret`,
  `Dream Stealer`,
  `Shiverin’ Dragon`,
  `Fallen Fish`,
  `Fallen Hook`,
  `New Pearl`,
  `Serpent’s Revenge`,
  `Silent Killer`,
  `Dirty Dragon`,
  `HellFish`,
  `Burning Dragon`,
  `Poseidon’s Revenge`,
  `Curse of Poseidon`,
  `Neptune’s Wave`,
  `Red Tsunami`,
  `Fallen Captain`,
  `Damp Queen`,
  `Fish Fryer`,
  `Dark Shark`,
  `Clumsy Sailor`,
  `Jewel of Atlantis`,
  `Jewel Theif`,
  `Dusty Anchor`,
  `Rusty Bell`,
  `Pretty Coral`,
  `Dreaming Wave`,
  `Tainted Dragon`,
  `Scurvy Wave`,
  `Damned Night`,
  `Squid Blaster`,
  `Rusty Cannon`,
  `Brave Titan`,
  `Stone Shark`,
  `Ghostly Death`,
  `Mystic Sirens`,
  `Pure Sirens`,
  `Devil’s Heart`,
  `Stone Angel`,
  `Fallen Titan`,
  `Wicked Folly`,
  `Deadly Destiny`,
  `Ulgy Kraken`,
  `Soulless Dragon`,
  `Royal Pearl`,
  `Deadly Squid`,
  `Neptune’s Teeth`,
  `Hellish Shark`,
  `Barbaric Ghost`,
  `Lost Mayflower`,
  `Lost Screams of Peter`,
  `Jewel Serpent`,
  `Speedy Slug`,
  `Sunken Seaweed`,
  "Sunken Whale",
];

const randomBoatName = () => {
  const randomNum = Math.round(Math.random() * boatNames.length);

  return boatNames[randomNum];
};

module.exports = { randomBoatName };
