const pirateName = [
  `Cap’n Dreadful`,
  `Captain Justeene`,
  `Captain Seadog`,
  `Captain MackCalabran`,
  `Captain Vex Totem`,
  `Captain Black Jack`,
  `Captain Blackbeard`,
  `Captain Silver-Tongue`,
  `Captain Silver-Hook`,
  `Admiral Davey`,
  `Admiral Williams`,
  `Captain Jolly`,
  `Captain O’Fish`,
  `Admiral Storm`,
  `Captain Booty`,
  `Captain Crabby`,
  `Captain Redbeard`,
  `Captain Puffypants`,
  `CaptainCannon`,
  `Admiral Spike`,
  `Admiral Wade`,
  `Captain Lazyjacks`,
  `Admiral Mullins`,
  `Captain Rattlebones`,
  `Cap’n Skully`,
  `Captain Crawford`,
  `Sir John Winters`,
  `Captain Vera Brave`,
  `Captain Liza callywag`,
  `Captain Cecila Jagger`,
  `Admiral Hawk`,
  `Captain Drake Deranged`,
  `Captain Slyvester Shadows`,
  `Admiral Simpson`,
  `Captain Deepsea Davey`,
  `Captain David Death`,
  `Captain Mildred McCoy`,
  `Captain Rivers McGee`,
  `Captain Julie Jagger`,
  `Captain Patty Price`,
  `Captain McKraken`,
  `Captain Van Horne`,
  `Captain Sandy Shores`,
  `Captain McFilthy`,
  `Captain Scurvyshorts`,
  `Captain Randell Red-Lord`,
  `Captain Fish-Lips`,
  `Admiral Henry Heart`,
  `Captain Renshaw Vance`,
  `Captain Eldar Nightwind`,
  `Cap’n Chipper Toes`,
];

const randomPirateName = () => {
  const randomNum = Math.round(Math.random() * pirateName.length);

  return pirateName[randomNum];
};

module.exports = { randomPirateName };
